/*
 * Copyright 2019 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */
/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
!!GlobalInfo
product: Pins v7.0
processor: MIMXRT685S
package_id: MIMXRT685SFVKB
mcu_data: ksdk2_0
processor_version: 0.0.2
pin_labels:
- {pin_num: G15, pin_signal: PIO1_1/FC4_SSEL2/SCT0_GPI2/SCT0_OUT8/CTIMER1_MAT0, label: 'FLEXSPI_B_DATA, 2'}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

#include "fsl_common.h"
#include "fsl_iopctl.h"
#include "fsl_gpio.h"
#include "pin_mux.h"


#define IOPCTL_PIO_ANAMUX_DI 0x00u        /*!<@brief Analog mux is disabled */
#define IOPCTL_PIO_FULLDRIVE_DI 0x00u     /*!<@brief Normal drive */
#define IOPCTL_PIO_FUNC1 0x01u            /*!<@brief Selects pin function 1 */
#define IOPCTL_PIO_FULLDRIVE_EN 0x0100u   /*!<@brief Full drive enable */
#define IOPCTL_PIO_FUNC0 0x00u            /*!<@brief Selects pin function 0 */
#define IOPCTL_PIO_FUNC5 0x05u            /*!<@brief Selects pin function 5 */
#define IOPCTL_PIO_FUNC6 0x06u            /*!<@brief Selects pin function 6 */
#define IOPCTL_PIO_INBUF_DI 0x00u         /*!<@brief Disable input buffer function */
#define IOPCTL_PIO_INBUF_EN 0x40u         /*!<@brief Enables input buffer function */
#define IOPCTL_PIO_INV_DI 0x00u           /*!<@brief Input function is not inverted */
#define IOPCTL_PIO_PSEDRAIN_DI 0x00u      /*!<@brief Pseudo Output Drain is disabled */
#define IOPCTL_PIO_PULLDOWN_EN 0x00u      /*!<@brief Enable pull-down function */
#define IOPCTL_PIO_PUPD_DI 0x00u          /*!<@brief Disable pull-up / pull-down function */
#define IOPCTL_PIO_SLEW_RATE_NORMAL 0x00u /*!<@brief Normal mode */

void BOARD_InitFlexSPI0BPins(void); /* Function assigned for the Cortex-M33 */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitBootPins
 * Description   : Calls initialization functions.
 *
 * END ****************************************************************************************************************/
void BOARD_InitBootPins (void)
{
    BOARD_InitUARTPins ();
    BOARD_InitFlexSPI0BPins ();
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitPins:
- options: {callFromInitBoot: 'true', coreID: cm33, enableClock: 'true'}
- pin_list:
  - {pin_num: G4, peripheral: FLEXCOMM0, signal: RXD_SDA_MOSI_DATA, pin_signal: PIO0_2/FC0_RXD_SDA_MOSI_DATA/CTIMER0_MAT2/I2S_BRIDGE_DATA_IN/SEC_PIO0_2, pupdena: disabled,
    pupdsel: pullDown, ibena: enabled, slew_rate: normal, drive: normal, amena: disabled, odena: disabled, iiena: disabled}
  - {pin_num: G2, peripheral: FLEXCOMM0, signal: TXD_SCL_MISO_WS, pin_signal: PIO0_1/FC0_TXD_SCL_MISO_WS/CTIMER0_MAT1/I2S_BRIDGE_WS_IN/SEC_PIO0_1, pupdena: disabled,
    pupdsel: pullDown, ibena: disabled, slew_rate: normal, drive: normal, amena: disabled, odena: disabled, iiena: disabled}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 */
void BOARD_InitUARTPins (void)
{

    const uint32_t port0_pin1_config = (IOPCTL_PIO_FUNC1 |			/* Pin is configured as FC0_TXD_SCL_MISO_WS */
                                        IOPCTL_PIO_PUPD_DI |		/* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |	/* Enable pull-down function */
                                        IOPCTL_PIO_INBUF_DI |		/* Disable input buffer function */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL |	/* Normal mode */
                                        IOPCTL_PIO_FULLDRIVE_DI |	/* Normal drive */
                                        IOPCTL_PIO_ANAMUX_DI |		/* Analog mux is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |	/* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_INV_DI);			/* Input function is not inverted */
    /* PORT0 PIN1 (coords: G2) is configured as FC0_TXD_SCL_MISO_WS */
    IOPCTL_PinMuxSet(IOPCTL, 0U, 1U, port0_pin1_config);

    const uint32_t port0_pin2_config = (IOPCTL_PIO_FUNC1 |			/* Pin is configured as FC0_RXD_SDA_MOSI_DATA */
                                        IOPCTL_PIO_PUPD_DI |		/* Disable pull-up / pull-down function */
                                        IOPCTL_PIO_PULLDOWN_EN |	/* Enable pull-down function */
                                        IOPCTL_PIO_INBUF_EN |		/* Enables input buffer function */
                                        IOPCTL_PIO_SLEW_RATE_NORMAL | /* Normal mode */
                                        IOPCTL_PIO_FULLDRIVE_DI |	/* Normal drive */
                                        IOPCTL_PIO_ANAMUX_DI |		/* Analog mux is disabled */
                                        IOPCTL_PIO_PSEDRAIN_DI |	/* Pseudo Output Drain is disabled */
                                        IOPCTL_PIO_INV_DI);			/* Input function is not inverted */
    /* PORT0 PIN2 (coords: G4) is configured as FC0_RXD_SDA_MOSI_DATA */
    IOPCTL_PinMuxSet(IOPCTL, 0U, 2U, port0_pin2_config);
}

/* clang-format off */
/*
 * TEXT BELOW IS USED AS SETTING FOR TOOLS *************************************
BOARD_InitFlexSPI0BPins:
- options: {callFromInitBoot: 'true', coreID: cm33, enableClock: 'true'}
- pin_list:
  - {pin_num: L2, peripheral: FLEXSPI, signal: FLEXSPI_B_DATA0, pin_signal: PIO1_11/HS_SPI_SCK/CTIMER2_MAT0/FLEXSPI0B_DATA0, ibena: enabled, drive: full}
  - {pin_num: M2, peripheral: FLEXSPI, signal: FLEXSPI_B_DATA1, pin_signal: PIO1_12/HS_SPI_MISO/CTIMER2_MAT1/FLEXSPI0B_DATA1, ibena: enabled, drive: full}
  - {pin_num: N1, peripheral: FLEXSPI, signal: FLEXSPI_B_DATA2, pin_signal: PIO1_13/HS_SPI_MOSI/CTIMER2_MAT2/FLEXSPI0B_DATA2, ibena: enabled, drive: full}
  - {pin_num: N2, peripheral: FLEXSPI, signal: FLEXSPI_B_DATA3, pin_signal: PIO1_14/HS_SPI_SSEL0/CTIMER2_MAT3/FLEXSPI0B_DATA3, ibena: enabled, drive: full}
  - {pin_num: U1, peripheral: FLEXSPI, signal: FLEXSPI_B_DATA4, pin_signal: PIO2_17/PDM_CLK23/FLEXSPI0B_DATA4, ibena: enabled, drive: full}
  - {pin_num: R2, peripheral: FLEXSPI, signal: FLEXSPI_B_DATA5, pin_signal: PIO2_18/PDM_CLK45/FLEXSPI0B_DATA5, ibena: enabled, drive: full}
  - {pin_num: P3, peripheral: FLEXSPI, signal: FLEXSPI_B_DATA6, pin_signal: PIO2_22/PDM_DATA45/FLEXSPI0B_DATA6, ibena: enabled, drive: full}
  - {pin_num: P5, peripheral: FLEXSPI, signal: FLEXSPI_B_DATA7, pin_signal: PIO2_23/PDM_DATA67/FLEXSPI0B_DATA7, ibena: enabled, drive: full}
  - {pin_num: U3, peripheral: FLEXSPI, signal: FLEXSPI_B_SCLK, pin_signal: PIO1_29/FLEXSPI0A_SS1_N/SCT0_OUT5/UTICK_CAP2/CTIMER_INP13/FLEXSPI0B_SCLK, ibena: enabled,
    drive: full}
  - {pin_num: T2, peripheral: FLEXSPI, signal: FLEXSPI_B_SS0_B, pin_signal: PIO2_19/PDM_CLK67/FLEXSPI0B_SS0_N, ibena: enabled, drive: full}
  - {pin_num: T3, peripheral: GPIO, signal: 'PIO2, 12', pin_signal: PIO2_12/SCT0_OUT6/CTIMER2_MAT2}
 * BE CAREFUL MODIFYING THIS COMMENT - IT IS YAML SETTINGS FOR TOOLS ***********
 */
/* clang-format on */

/* FUNCTION ************************************************************************************************************
 *
 * Function Name : BOARD_InitFlexSPI0BPins
 * Description   : Configures pin routing and optionally pin electrical features.
 *
 * END ****************************************************************************************************************/
/* Function assigned for the Cortex-M33 */
void BOARD_InitQuadSPIPins (void)
{
    GPIO_PortInit (GPIO, 1);
    GPIO_PortInit (GPIO, 2);
        /* Define the init structure for the reset pin*/
    gpio_pin_config_t reset_config = {
        kGPIO_DigitalOutput,
        1,
    };
    GPIO_PinInit  (GPIO, 2, 12, &reset_config);

    const uint32_t port1_pin11_config = (IOPCTL_PIO_FUNC6 |			/* Pin is configured as FLEXSPI0B_DATA0 */
                                         IOPCTL_PIO_PUPD_DI |		/* Disable pull-up / pull-down function */
                                         IOPCTL_PIO_PULLDOWN_EN |	/* Enable pull-down function */
                                         IOPCTL_PIO_INBUF_EN |		/* Enables input buffer function */
                                         IOPCTL_PIO_SLEW_RATE_NORMAL |/* Normal mode */
                                         IOPCTL_PIO_FULLDRIVE_EN |	/* Full drive enable */
                                         IOPCTL_PIO_ANAMUX_DI |		/* Analog mux is disabled */
                                         IOPCTL_PIO_PSEDRAIN_DI |	/* Pseudo Output Drain is disabled */
                                         IOPCTL_PIO_INV_DI);		/* Input function is not inverted */
    /* PORT1 PIN11 (coords: L2) is configured as FLEXSPI0B_DATA0 */
    IOPCTL_PinMuxSet(IOPCTL, 1U, 11U, port1_pin11_config);

    const uint32_t port1_pin12_config = (IOPCTL_PIO_FUNC6 |			/* Pin is configured as FLEXSPI0B_DATA1 */
                                         IOPCTL_PIO_PUPD_DI |		/* Disable pull-up / pull-down function */
                                         IOPCTL_PIO_PULLDOWN_EN |	/* Enable pull-down function */
                                         IOPCTL_PIO_INBUF_EN |		/* Enables input buffer function */
                                         IOPCTL_PIO_SLEW_RATE_NORMAL |/* Normal mode */
                                         IOPCTL_PIO_FULLDRIVE_EN |	/* Full drive enable */
                                         IOPCTL_PIO_ANAMUX_DI |		/* Analog mux is disabled */
                                         IOPCTL_PIO_PSEDRAIN_DI |	/* Pseudo Output Drain is disabled */
                                         IOPCTL_PIO_INV_DI);		/* Input function is not inverted */
    /* PORT1 PIN12 (coords: M2) is configured as FLEXSPI0B_DATA1 */
    IOPCTL_PinMuxSet(IOPCTL, 1U, 12U, port1_pin12_config);

    const uint32_t port1_pin13_config = (IOPCTL_PIO_FUNC6 |			/* Pin is configured as FLEXSPI0B_DATA2 */
                                         IOPCTL_PIO_PUPD_DI |		/* Disable pull-up / pull-down function */
                                         IOPCTL_PIO_PULLDOWN_EN |	/* Enable pull-down function */
                                         IOPCTL_PIO_INBUF_EN |		/* Enables input buffer function */
                                         IOPCTL_PIO_SLEW_RATE_NORMAL |/* Normal mode */
                                         IOPCTL_PIO_FULLDRIVE_EN |	/* Full drive enable */
                                         IOPCTL_PIO_ANAMUX_DI |		/* Analog mux is disabled */
                                         IOPCTL_PIO_PSEDRAIN_DI |	/* Pseudo Output Drain is disabled */
                                         IOPCTL_PIO_INV_DI);		/* Input function is not inverted */
    /* PORT1 PIN13 (coords: N1) is configured as FLEXSPI0B_DATA2 */
    IOPCTL_PinMuxSet(IOPCTL, 1U, 13U, port1_pin13_config);

    const uint32_t port1_pin14_config = (IOPCTL_PIO_FUNC6 |			/* Pin is configured as FLEXSPI0B_DATA3 */
                                         IOPCTL_PIO_PUPD_DI |		/* Disable pull-up / pull-down function */
                                         IOPCTL_PIO_PULLDOWN_EN |	/* Enable pull-down function */
                                         IOPCTL_PIO_INBUF_EN |		/* Enables input buffer function */
                                         IOPCTL_PIO_SLEW_RATE_NORMAL |/* Normal mode */
                                         IOPCTL_PIO_FULLDRIVE_EN |	/* Full drive enable */
                                         IOPCTL_PIO_ANAMUX_DI |		/* Analog mux is disabled */
                                         IOPCTL_PIO_PSEDRAIN_DI |	/* Pseudo Output Drain is disabled */
                                         IOPCTL_PIO_INV_DI);		/* Input function is not inverted */
    /* PORT1 PIN14 (coords: N2) is configured as FLEXSPI0B_DATA3 */
    IOPCTL_PinMuxSet(IOPCTL, 1U, 14U, port1_pin14_config);

    const uint32_t port1_pin29_config = (IOPCTL_PIO_FUNC5 |			/* Pin is configured as FLEXSPI0B_SCLK */
                                         IOPCTL_PIO_PUPD_DI |		/* Disable pull-up / pull-down function */
                                         IOPCTL_PIO_PULLDOWN_EN |	/* Enable pull-down function */
                                         IOPCTL_PIO_INBUF_EN |		/* Enables input buffer function */
                                         IOPCTL_PIO_SLEW_RATE_NORMAL |	/* Normal mode */
                                         IOPCTL_PIO_FULLDRIVE_EN |	/* Full drive enable */
                                         IOPCTL_PIO_ANAMUX_DI |		/* Analog mux is disabled */
                                         IOPCTL_PIO_PSEDRAIN_DI |	/* Pseudo Output Drain is disabled */
                                         IOPCTL_PIO_INV_DI);		/* Input function is not inverted */
    /* PORT1 PIN29 (coords: U3) is configured as FLEXSPI0B_SCLK */
    IOPCTL_PinMuxSet(IOPCTL, 1U, 29U, port1_pin29_config);

    const uint32_t port2_pin12_config = (IOPCTL_PIO_FUNC0 |			/* Pin is configured as PIO2_12 */
                                         IOPCTL_PIO_PUPD_DI |		/* Disable pull-up / pull-down function */
                                         IOPCTL_PIO_PULLDOWN_EN |	/* Enable pull-down function */
                                         IOPCTL_PIO_INBUF_DI |		/* Disable input buffer function */
                                         IOPCTL_PIO_SLEW_RATE_NORMAL |/* Normal mode */
                                         IOPCTL_PIO_FULLDRIVE_DI |	/* Normal drive */
                                         IOPCTL_PIO_ANAMUX_DI |		/* Analog mux is disabled */
                                         IOPCTL_PIO_PSEDRAIN_DI |	/* Pseudo Output Drain is disabled */
                                         IOPCTL_PIO_INV_DI);		/* Input function is not inverted */
    /* PORT2 PIN12 (coords: T3) is configured as PIO2_12 */	// MK: Reset Signal
    IOPCTL_PinMuxSet(IOPCTL, 2U, 12U, port2_pin12_config);
}

void BOARD_InitOctaSPIPins (void)
{
    const uint32_t port2_pin17_config = (IOPCTL_PIO_FUNC6 |			/* Pin is configured as FLEXSPI0B_DATA4 */
                                         IOPCTL_PIO_PUPD_DI |		/* Disable pull-up / pull-down function */
                                         IOPCTL_PIO_PULLDOWN_EN |	/* Enable pull-down function */
                                         IOPCTL_PIO_INBUF_EN |		/* Enables input buffer function */
                                         IOPCTL_PIO_SLEW_RATE_NORMAL |/* Normal mode */
                                         IOPCTL_PIO_FULLDRIVE_EN |	/* Full drive enable */
                                         IOPCTL_PIO_ANAMUX_DI |		/* Analog mux is disabled */
                                         IOPCTL_PIO_PSEDRAIN_DI |	/* Pseudo Output Drain is disabled */
                                         IOPCTL_PIO_INV_DI);		/* Input function is not inverted */
    /* PORT2 PIN17 (coords: U1) is configured as FLEXSPI0B_DATA4 */
    IOPCTL_PinMuxSet(IOPCTL, 2U, 17U, port2_pin17_config);

    const uint32_t port2_pin18_config = (IOPCTL_PIO_FUNC6 |			/* Pin is configured as FLEXSPI0B_DATA5 */
                                         IOPCTL_PIO_PUPD_DI |		/* Disable pull-up / pull-down function */
                                         IOPCTL_PIO_PULLDOWN_EN |	/* Enable pull-down function */
                                         IOPCTL_PIO_INBUF_EN |		/* Enables input buffer function */
                                         IOPCTL_PIO_SLEW_RATE_NORMAL |/* Normal mode */
                                         IOPCTL_PIO_FULLDRIVE_EN |	/* Full drive enable */
                                         IOPCTL_PIO_ANAMUX_DI |		/* Analog mux is disabled */
                                         IOPCTL_PIO_PSEDRAIN_DI |	/* Pseudo Output Drain is disabled */
                                         IOPCTL_PIO_INV_DI);		/* Input function is not inverted */
    /* PORT2 PIN18 (coords: R2) is configured as FLEXSPI0B_DATA5 */
    IOPCTL_PinMuxSet(IOPCTL, 2U, 18U, port2_pin18_config);

    const uint32_t port2_pin19_config = (IOPCTL_PIO_FUNC6 |			/* Pin is configured as FLEXSPI0B_SS0_N */
                                         IOPCTL_PIO_PUPD_DI |		/* Disable pull-up / pull-down function */
                                         IOPCTL_PIO_PULLDOWN_EN |	/* Enable pull-down function */
                                         IOPCTL_PIO_INBUF_EN |		/* Enables input buffer function */
                                         IOPCTL_PIO_SLEW_RATE_NORMAL |/* Normal mode */
                                         IOPCTL_PIO_FULLDRIVE_EN |	/* Full drive enable */
                                         IOPCTL_PIO_ANAMUX_DI |		/* Analog mux is disabled */
                                         IOPCTL_PIO_PSEDRAIN_DI |	/* Pseudo Output Drain is disabled */
                                         IOPCTL_PIO_INV_DI);		/* Input function is not inverted */
    /* PORT2 PIN19 (coords: T2) is configured as FLEXSPI0B_SS0_N */
    IOPCTL_PinMuxSet(IOPCTL, 2U, 19U, port2_pin19_config);

    const uint32_t port2_pin22_config = (IOPCTL_PIO_FUNC6 |			/* Pin is configured as FLEXSPI0B_DATA6 */
                                         IOPCTL_PIO_PUPD_DI |		/* Disable pull-up / pull-down function */
                                         IOPCTL_PIO_PULLDOWN_EN |	/* Enable pull-down function */
                                         IOPCTL_PIO_INBUF_EN |		/* Enables input buffer function */
                                         IOPCTL_PIO_SLEW_RATE_NORMAL |	/* Normal mode */
                                         IOPCTL_PIO_FULLDRIVE_EN |	/* Full drive enable */
                                         IOPCTL_PIO_ANAMUX_DI |		/* Analog mux is disabled */
                                         IOPCTL_PIO_PSEDRAIN_DI |	/* Pseudo Output Drain is disabled */
                                         IOPCTL_PIO_INV_DI);		/* Input function is not inverted */
    /* PORT2 PIN22 (coords: P3) is configured as FLEXSPI0B_DATA6 */
    IOPCTL_PinMuxSet(IOPCTL, 2U, 22U, port2_pin22_config);

    const uint32_t port2_pin23_config = (IOPCTL_PIO_FUNC6 |			/* Pin is configured as FLEXSPI0B_DATA7 */
                                         IOPCTL_PIO_PUPD_DI |		/* Disable pull-up / pull-down function */
                                         IOPCTL_PIO_PULLDOWN_EN |	/* Enable pull-down function */
                                         IOPCTL_PIO_INBUF_EN |		/* Enables input buffer function */
                                         IOPCTL_PIO_SLEW_RATE_NORMAL |	/* Normal mode */
                                         IOPCTL_PIO_FULLDRIVE_EN |	/* Full drive enable */
                                         IOPCTL_PIO_ANAMUX_DI |		/* Analog mux is disabled */
                                         IOPCTL_PIO_PSEDRAIN_DI |	/* Pseudo Output Drain is disabled */
                                         IOPCTL_PIO_INV_DI);		/* Input function is not inverted */
    /* PORT2 PIN23 (coords: P5) is configured as FLEXSPI0B_DATA7 */
    IOPCTL_PinMuxSet(IOPCTL, 2U, 23U, port2_pin23_config);

    BOARD_InitQuadSPIPins ();
}

void BOARD_PerformJEDECReset (void)
{
	const uint32_t GpioConfig = IOPCTL_PIO_FUNC0 |				/* Pin is configured as PIO2_12 */
                                IOPCTL_PIO_PUPD_DI |			/* Disable pull-up / pull-down function */
                                IOPCTL_PIO_PULLDOWN_EN |		/* Enable pull-down function */
                                IOPCTL_PIO_INBUF_DI |			/* Disable input buffer function */
                                IOPCTL_PIO_SLEW_RATE_NORMAL |	/* Normal mode */
                                IOPCTL_PIO_FULLDRIVE_DI |		/* Normal drive */
                                IOPCTL_PIO_ANAMUX_DI |			/* Analog mux is disabled */
                                IOPCTL_PIO_PSEDRAIN_DI |		/* Pseudo Output Drain is disabled */
                                IOPCTL_PIO_INV_DI;				/* Input function is not inverted */


	GPIO_PortInit (GPIO, 1);
	GPIO_PortInit (GPIO, 2);

	IOPCTL_PinMuxSet(IOPCTL, 2U, 19U, GpioConfig);	// SS0
	IOPCTL_PinMuxSet(IOPCTL, 1U, 11U, GpioConfig);	// Data0
	IOPCTL_PinMuxSet(IOPCTL, 1U, 29U, GpioConfig);	// CLK

	// Set the direction of 3 pins used in JEDEC reset to output
    gpio_pin_config_t jreset_pin_config = {kGPIO_DigitalOutput, 1};
	GPIO_PinInit (GPIO, 2U, 19U, &jreset_pin_config); // CS
	GPIO_PinInit (GPIO, 1U, 11U, &jreset_pin_config); // SI/IO0
	GPIO_PinInit (GPIO, 1U, 29U, &jreset_pin_config); // SCK

	// Perform a reset sequence:
	// CS goes low 4 times with alternating values of SOUT
	// SCK is drive low or high and must stay in one state
	GPIO_PinWrite (GPIO, 1U, 29U, 0); // set SCK low
	for (uint32_t i = 0; i < 4; i++)
	{
		// drive CS low
		GPIO_PinWrite (GPIO, 2U, 19U, 0);
		for (int j=0; j<100; j++);
		// drive SI low or high: alternate its state every iteration
		GPIO_PinWrite (GPIO, 1U, 11U, (i&1));
		// drive CS high; SI state will be captured on the CS rising edge
		GPIO_PinWrite (GPIO, 2U, 19U, 1);
		for (int j=0; j<100; j++)
			;
	}
}

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/


