/** Loader for iMXRT-Family
Copyright (C) 2019-2024 Markus Klein
https://github.com/Masmiseim36/iMXRT

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice,
   this list of conditions and the following disclaimer.

THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT
SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING
IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY
OF SUCH DAMAGE. */

#include "fsl_common.h"
#include "fsl_iomuxc.h"
#include "fsl_gpio.h"
#include "pin_mux.h"
#include "board.h"

/*! BOARD_InitUARTPins
Set pin muxing and configure electrical properties for the UART */
void BOARD_InitUARTPins (void)
{
	CLOCK_EnableClock   (kCLOCK_Iomuxc);

	#if DEBUG_CONSOLE_UART_INDEX == 1
		IOMUXC_SetPinMux    (IOMUXC_GPIO_AD_24_LPUART1_TXD, 0U);
		IOMUXC_SetPinConfig (IOMUXC_GPIO_AD_24_LPUART1_TXD, IOMUXC_SW_PAD_CTL_PAD_DSE_MASK);

		IOMUXC_SetPinMux    (IOMUXC_GPIO_AD_25_LPUART1_RXD, 0U);
		IOMUXC_SetPinConfig (IOMUXC_GPIO_AD_25_LPUART1_RXD, IOMUXC_SW_PAD_CTL_PAD_DSE_MASK);
	#elif DEBUG_CONSOLE_UART_INDEX == 6
		IOMUXC_SetPinMux    (IOMUXC_GPIO_EMC_B1_40_LPUART6_TXD, 0U);
		IOMUXC_SetPinConfig (IOMUXC_GPIO_EMC_B1_40_LPUART6_TXD, 0x0u);

		IOMUXC_SetPinMux    (IOMUXC_GPIO_EMC_B1_41_LPUART6_RXD, 1U);
		IOMUXC_SetPinConfig (IOMUXC_GPIO_EMC_B1_41_LPUART6_RXD, 0x0u);
	#else
		#error "Unknown serial port"
	#endif
}

/* All FlexSPI1-Pins for iMXRT1170
IOMUXC_GPIO_AD_17_FLEXSPI1_A_DQS		IOMUXC_GPIO_EMC_B2_18_FLEXSPI1_A_DQS		IOMUXC_GPIO_SD_B2_05_FLEXSPI1_A_DQS
IOMUXC_GPIO_AD_18_FLEXSPI1_A_SS0_B		IOMUXC_GPIO_SD_B2_06_FLEXSPI1_A_SS0_B
IOMUXC_GPIO_AD_19_FLEXSPI1_A_SCLK		IOMUXC_GPIO_SD_B2_07_FLEXSPI1_A_SCLK
IOMUXC_GPIO_AD_20_FLEXSPI1_A_DATA00		IOMUXC_GPIO_SD_B2_08_FLEXSPI1_A_DATA00
IOMUXC_GPIO_AD_21_FLEXSPI1_A_DATA01		IOMUXC_GPIO_SD_B2_09_FLEXSPI1_A_DATA01
IOMUXC_GPIO_AD_22_FLEXSPI1_A_DATA02		IOMUXC_GPIO_SD_B2_10_FLEXSPI1_A_DATA02
IOMUXC_GPIO_AD_23_FLEXSPI1_A_DATA03		IOMUXC_GPIO_SD_B2_11_FLEXSPI1_A_DATA03
IOMUXC_GPIO_AD_12_FLEXSPI1_B_DATA03		IOMUXC_GPIO_SD_B2_00_FLEXSPI1_B_DATA03
IOMUXC_GPIO_AD_13_FLEXSPI1_B_DATA02		IOMUXC_GPIO_SD_B2_01_FLEXSPI1_B_DATA02
IOMUXC_GPIO_AD_14_FLEXSPI1_B_DATA01		IOMUXC_GPIO_SD_B2_02_FLEXSPI1_B_DATA01
IOMUXC_GPIO_AD_15_FLEXSPI1_B_DATA00		IOMUXC_GPIO_SD_B2_03_FLEXSPI1_B_DATA00
IOMUXC_GPIO_AD_16_FLEXSPI1_B_SCLK		IOMUXC_GPIO_SD_B2_04_FLEXSPI1_B_SCLK
IOMUXC_GPIO_AD_35_FLEXSPI1_B_SS1_B
IOMUXC_GPIO_SD_B1_02_FLEXSPI1_A_SS1_B	IOMUXC_GPIO_SD_B2_04_FLEXSPI1_A_SS1_B
IOMUXC_GPIO_SD_B1_03_FLEXSPI1_B_SS1_B
IOMUXC_GPIO_SD_B1_04_FLEXSPI1_B_SS0_B	IOMUXC_GPIO_SD_B2_05_FLEXSPI1_B_SS0_B
IOMUXC_GPIO_SD_B1_05_FLEXSPI1_B_DQS  */


/** BOARD_InitQuadSPIPins
Set pin muxing and configure electrical properties for QSPI */
void BOARD_InitQuadSPI1Pins (void)
{
	CLOCK_EnableClock (kCLOCK_Iomuxc);

	IOMUXC_SetPinMux    (IOMUXC_GPIO_SD_B2_05_FLEXSPI1_A_DQS, 1U);
	IOMUXC_SetPinConfig (IOMUXC_GPIO_SD_B2_05_FLEXSPI1_A_DQS, IOMUXC_SW_PAD_CTL_PAD_PUS_MASK | IOMUXC_SW_PAD_CTL_PAD_DSE_MASK);

	IOMUXC_SetPinMux    (IOMUXC_GPIO_SD_B2_06_FLEXSPI1_A_SS0_B, 1U);
	IOMUXC_SetPinConfig (IOMUXC_GPIO_SD_B2_06_FLEXSPI1_A_SS0_B, IOMUXC_SW_PAD_CTL_PAD_PUS_MASK | IOMUXC_SW_PAD_CTL_PAD_DSE_MASK);

	IOMUXC_SetPinMux    (IOMUXC_GPIO_SD_B2_07_FLEXSPI1_A_SCLK, 1U);
	IOMUXC_SetPinConfig (IOMUXC_GPIO_SD_B2_07_FLEXSPI1_A_SCLK, IOMUXC_SW_PAD_CTL_PAD_PUS_MASK | IOMUXC_SW_PAD_CTL_PAD_DSE_MASK);

	IOMUXC_SetPinMux    (IOMUXC_GPIO_SD_B2_08_FLEXSPI1_A_DATA00, 1U);
	IOMUXC_SetPinConfig (IOMUXC_GPIO_SD_B2_08_FLEXSPI1_A_DATA00, IOMUXC_SW_PAD_CTL_PAD_PUS_MASK | IOMUXC_SW_PAD_CTL_PAD_DSE_MASK);

	IOMUXC_SetPinMux    (IOMUXC_GPIO_SD_B2_09_FLEXSPI1_A_DATA01, 1U);
	IOMUXC_SetPinConfig (IOMUXC_GPIO_SD_B2_09_FLEXSPI1_A_DATA01, IOMUXC_SW_PAD_CTL_PAD_PUS_MASK | IOMUXC_SW_PAD_CTL_PAD_DSE_MASK);

	IOMUXC_SetPinMux    (IOMUXC_GPIO_SD_B2_10_FLEXSPI1_A_DATA02, 1U);
	IOMUXC_SetPinConfig (IOMUXC_GPIO_SD_B2_10_FLEXSPI1_A_DATA02, IOMUXC_SW_PAD_CTL_PAD_PUS_MASK | IOMUXC_SW_PAD_CTL_PAD_DSE_MASK);

	IOMUXC_SetPinMux    (IOMUXC_GPIO_SD_B2_11_FLEXSPI1_A_DATA03, 1U);
	IOMUXC_SetPinConfig (IOMUXC_GPIO_SD_B2_11_FLEXSPI1_A_DATA03, IOMUXC_SW_PAD_CTL_PAD_PUS_MASK | IOMUXC_SW_PAD_CTL_PAD_DSE_MASK);
}

/** BOARD_InitOctaSPIPins
Set pin muxing and configure electrical properties for Hyperflash/OctaSPI */ 
void BOARD_InitOctaSPI1Pins (void)
{
	IOMUXC_SetPinMux    (IOMUXC_GPIO_SD_B2_00_FLEXSPI1_B_DATA03, 1U);
	IOMUXC_SetPinConfig (IOMUXC_GPIO_SD_B2_00_FLEXSPI1_B_DATA03, IOMUXC_SW_PAD_CTL_PAD_PUS_MASK | IOMUXC_SW_PAD_CTL_PAD_DSE_MASK);

	IOMUXC_SetPinMux    (IOMUXC_GPIO_SD_B2_01_FLEXSPI1_B_DATA02, 1U);
	IOMUXC_SetPinConfig (IOMUXC_GPIO_SD_B2_01_FLEXSPI1_B_DATA02, IOMUXC_SW_PAD_CTL_PAD_PUS_MASK | IOMUXC_SW_PAD_CTL_PAD_DSE_MASK);

	IOMUXC_SetPinMux    (IOMUXC_GPIO_SD_B2_02_FLEXSPI1_B_DATA01, 1U);
	IOMUXC_SetPinConfig (IOMUXC_GPIO_SD_B2_02_FLEXSPI1_B_DATA01, IOMUXC_SW_PAD_CTL_PAD_PUS_MASK | IOMUXC_SW_PAD_CTL_PAD_DSE_MASK);

	IOMUXC_SetPinMux    (IOMUXC_GPIO_SD_B2_03_FLEXSPI1_B_DATA00, 1U);
	IOMUXC_SetPinConfig (IOMUXC_GPIO_SD_B2_03_FLEXSPI1_B_DATA00, IOMUXC_SW_PAD_CTL_PAD_PUS_MASK | IOMUXC_SW_PAD_CTL_PAD_DSE_MASK);

	IOMUXC_SetPinMux    (IOMUXC_GPIO_SD_B2_04_FLEXSPI1_B_SCLK, 1U);
	IOMUXC_SetPinConfig (IOMUXC_GPIO_SD_B2_04_FLEXSPI1_B_SCLK, IOMUXC_SW_PAD_CTL_PAD_PUS_MASK | IOMUXC_SW_PAD_CTL_PAD_DSE_MASK);

	BOARD_InitQuadSPI1Pins ();
}

void BOARD_PerformJEDECReset_FlexSPI1 (void)
{
	gpio_pin_config_t jreset_pin_config = 
	{
		kGPIO_DigitalOutput, 1, kGPIO_NoIntmode
	};

	// Configure the 3 pins used in JEDEC reset as GPIOs
	IOMUXC_SetPinMux (IOMUXC_GPIO_SD_B2_06_GPIO_MUX4_IO15, 1);	// IOMUXC_GPIO_SD_B2_06_FLEXSPI1_A_SS0_B	-	IOMUXC_GPIO_SD_B2_06_GPIO10_IO15
	IOMUXC_SetPinMux (IOMUXC_GPIO_SD_B2_08_GPIO_MUX4_IO17, 1);	// IOMUXC_GPIO_SD_B2_08_FLEXSPI1_A_DATA00	-	IOMUXC_GPIO_SD_B2_08_GPIO10_IO17
	IOMUXC_SetPinMux (IOMUXC_GPIO_SD_B2_07_GPIO_MUX4_IO16, 1);	// IOMUXC_GPIO_SD_B2_07_FLEXSPI1_A_SCLK		-	IOMUXC_GPIO_SD_B2_07_GPIO10_IO16

	// Set the direction of 3 pins used in JEDEC reset to output
	GPIO_PinInit (GPIO4, 15, &jreset_pin_config); // CS
	GPIO_PinInit (GPIO4, 17, &jreset_pin_config); // SI/IO0
	GPIO_PinInit (GPIO4, 16, &jreset_pin_config); // SCK


	// Perform a reset sequence:
	// CS goes low 4 times with alternating values of SOUT
	// SCK is drive low or high and must stay in one state
	GPIO_WritePinOutput (GPIO4, 16, 0); // set SCK low
	for (uint32_t i = 0; i < 4; i++)
	{
		// drive CS low
		GPIO_WritePinOutput (GPIO4, 15, 0);
		SDK_DelayAtLeastUs (1, SystemCoreClock);
		// drive SI low or high: alternate its state every iteration
		GPIO_WritePinOutput (GPIO4, 17, (i&1));
		// drive CS high; SI state will be captured on the CS rising edge
		GPIO_WritePinOutput (GPIO4, 15, 1);
		SDK_DelayAtLeastUs (1, SystemCoreClock);
	}

	SDK_DelayAtLeastUs (110, SystemCoreClock);
}

/* All FlexSPI2-Pins for iMXRT1170
IOMUXC_GPIO_EMC_B2_10_FLEXSPI2_A_SCLK		IOMUXC_GPIO_SD_B1_01_FLEXSPI2_A_SCLK
IOMUXC_GPIO_EMC_B2_11_FLEXSPI2_A_SS0_B		IOMUXC_GPIO_SD_B1_00_FLEXSPI2_A_SS0_B
IOMUXC_GPIO_EMC_B2_12_FLEXSPI2_A_DQS
IOMUXC_GPIO_EMC_B2_13_FLEXSPI2_A_DATA00		IOMUXC_GPIO_SD_B1_02_FLEXSPI2_A_DATA00
IOMUXC_GPIO_EMC_B2_14_FLEXSPI2_A_DATA01		IOMUXC_GPIO_SD_B1_03_FLEXSPI2_A_DATA01
IOMUXC_GPIO_EMC_B2_15_FLEXSPI2_A_DATA02		IOMUXC_GPIO_SD_B1_04_FLEXSPI2_A_DATA02
IOMUXC_GPIO_EMC_B2_16_FLEXSPI2_A_DATA03		IOMUXC_GPIO_SD_B1_05_FLEXSPI2_A_DATA03
IOMUXC_GPIO_EMC_B2_17_FLEXSPI2_A_DATA04
IOMUXC_GPIO_EMC_B2_18_FLEXSPI2_A_DATA05
IOMUXC_GPIO_EMC_B2_19_FLEXSPI2_A_DATA06
IOMUXC_GPIO_EMC_B2_20_FLEXSPI2_A_DATA07
IOMUXC_GPIO_EMC_B1_41_FLEXSPI2_B_DATA07
IOMUXC_GPIO_EMC_B2_00_FLEXSPI2_B_DATA06
IOMUXC_GPIO_EMC_B2_01_FLEXSPI2_B_DATA05
IOMUXC_GPIO_EMC_B2_02_FLEXSPI2_B_DATA04
IOMUXC_GPIO_EMC_B2_03_FLEXSPI2_B_DATA03
IOMUXC_GPIO_EMC_B2_04_FLEXSPI2_B_DATA02
IOMUXC_GPIO_EMC_B2_05_FLEXSPI2_B_DATA01
IOMUXC_GPIO_EMC_B2_06_FLEXSPI2_B_DATA00
IOMUXC_GPIO_EMC_B2_07_FLEXSPI2_B_DQS
IOMUXC_GPIO_EMC_B2_08_FLEXSPI2_B_SS0_B
IOMUXC_GPIO_EMC_B2_09_FLEXSPI2_B_SCLK
IOMUXC_GPIO_AD_00_FLEXSPI2_B_SS1_B
IOMUXC_GPIO_AD_01_FLEXSPI2_A_SS1_B */

/** BOARD_InitQuadSPI2Pins
Set pin muxing and configure electrical properties for QSPI */
void BOARD_InitQuadSPI2Pins (void)
{
	CLOCK_EnableClock (kCLOCK_Iomuxc);

	IOMUXC_SetPinMux    (IOMUXC_GPIO_EMC_B2_12_FLEXSPI2_A_DQS, 1U);
	IOMUXC_SetPinConfig (IOMUXC_GPIO_EMC_B2_12_FLEXSPI2_A_DQS, IOMUXC_SW_PAD_CTL_PAD_PUS_MASK | IOMUXC_SW_PAD_CTL_PAD_DSE_MASK);

	IOMUXC_SetPinMux    (IOMUXC_GPIO_EMC_B2_11_FLEXSPI2_A_SS0_B, 1U);
	IOMUXC_SetPinConfig (IOMUXC_GPIO_EMC_B2_11_FLEXSPI2_A_SS0_B, IOMUXC_SW_PAD_CTL_PAD_PUS_MASK | IOMUXC_SW_PAD_CTL_PAD_DSE_MASK);

	IOMUXC_SetPinMux    (IOMUXC_GPIO_EMC_B2_10_FLEXSPI2_A_SCLK, 1U);
	IOMUXC_SetPinConfig (IOMUXC_GPIO_EMC_B2_10_FLEXSPI2_A_SCLK, IOMUXC_SW_PAD_CTL_PAD_PUS_MASK | IOMUXC_SW_PAD_CTL_PAD_DSE_MASK);

	IOMUXC_SetPinMux    (IOMUXC_GPIO_EMC_B2_13_FLEXSPI2_A_DATA00, 1U);
	IOMUXC_SetPinConfig (IOMUXC_GPIO_EMC_B2_13_FLEXSPI2_A_DATA00, IOMUXC_SW_PAD_CTL_PAD_PUS_MASK | IOMUXC_SW_PAD_CTL_PAD_DSE_MASK);

	IOMUXC_SetPinMux    (IOMUXC_GPIO_EMC_B2_14_FLEXSPI2_A_DATA01, 1U);
	IOMUXC_SetPinConfig (IOMUXC_GPIO_EMC_B2_14_FLEXSPI2_A_DATA01, IOMUXC_SW_PAD_CTL_PAD_PUS_MASK | IOMUXC_SW_PAD_CTL_PAD_DSE_MASK);

	IOMUXC_SetPinMux    (IOMUXC_GPIO_EMC_B2_15_FLEXSPI2_A_DATA02, 1U);
	IOMUXC_SetPinConfig (IOMUXC_GPIO_EMC_B2_15_FLEXSPI2_A_DATA02, IOMUXC_SW_PAD_CTL_PAD_PUS_MASK | IOMUXC_SW_PAD_CTL_PAD_DSE_MASK);

	IOMUXC_SetPinMux    (IOMUXC_GPIO_EMC_B2_16_FLEXSPI2_A_DATA03, 1U);
	IOMUXC_SetPinConfig (IOMUXC_GPIO_EMC_B2_16_FLEXSPI2_A_DATA03, IOMUXC_SW_PAD_CTL_PAD_PUS_MASK | IOMUXC_SW_PAD_CTL_PAD_DSE_MASK);
}

/** BOARD_InitOctaSPI2Pins
Set pin muxing and configure electrical properties for Hyperflash/OctaSPI */ 
void BOARD_InitOctaSPI2Pins (void)
{
	IOMUXC_SetPinMux    (IOMUXC_GPIO_EMC_B2_17_FLEXSPI2_A_DATA04, 1U);
	IOMUXC_SetPinConfig (IOMUXC_GPIO_EMC_B2_17_FLEXSPI2_A_DATA04, IOMUXC_SW_PAD_CTL_PAD_PUS_MASK | IOMUXC_SW_PAD_CTL_PAD_DSE_MASK);

	IOMUXC_SetPinMux    (IOMUXC_GPIO_EMC_B2_18_FLEXSPI2_A_DATA05, 1U);
	IOMUXC_SetPinConfig (IOMUXC_GPIO_EMC_B2_18_FLEXSPI2_A_DATA05, IOMUXC_SW_PAD_CTL_PAD_PUS_MASK | IOMUXC_SW_PAD_CTL_PAD_DSE_MASK);

	IOMUXC_SetPinMux    (IOMUXC_GPIO_EMC_B2_19_FLEXSPI2_A_DATA06, 1U);
	IOMUXC_SetPinConfig (IOMUXC_GPIO_EMC_B2_19_FLEXSPI2_A_DATA06, IOMUXC_SW_PAD_CTL_PAD_PUS_MASK | IOMUXC_SW_PAD_CTL_PAD_DSE_MASK);

	IOMUXC_SetPinMux    (IOMUXC_GPIO_EMC_B2_20_FLEXSPI2_A_DATA07, 1U);
	IOMUXC_SetPinConfig (IOMUXC_GPIO_EMC_B2_20_FLEXSPI2_A_DATA07, IOMUXC_SW_PAD_CTL_PAD_PUS_MASK | IOMUXC_SW_PAD_CTL_PAD_DSE_MASK);

	IOMUXC_SetPinMux    (IOMUXC_GPIO_EMC_B2_09_FLEXSPI2_B_SCLK, 1U);
	IOMUXC_SetPinConfig (IOMUXC_GPIO_EMC_B2_09_FLEXSPI2_B_SCLK, IOMUXC_SW_PAD_CTL_PAD_PUS_MASK | IOMUXC_SW_PAD_CTL_PAD_DSE_MASK);

	BOARD_InitQuadSPI2Pins ();
}

void BOARD_PerformJEDECReset_FlexSPI2 (void)
{
	gpio_pin_config_t jreset_pin_config = 
	{
		kGPIO_DigitalOutput, 1, kGPIO_NoIntmode
	};

	// Configure the 3 pins used in JEDEC reset as GPIOs
	IOMUXC_SetPinMux (IOMUXC_GPIO_EMC_B2_11_GPIO_MUX2_IO21, 1);	// IOMUXC_GPIO_EMC_B2_11_FLEXSPI2_A_SS0_B	-	IOMUXC_GPIO_SD_B1_00_FLEXSPI2_A_SS0_B
	IOMUXC_SetPinMux (IOMUXC_GPIO_EMC_B2_13_GPIO_MUX2_IO23, 1);	// IOMUXC_GPIO_EMC_B2_13_FLEXSPI2_A_DATA00	-	IOMUXC_GPIO_SD_B1_02_FLEXSPI2_A_DATA00
	IOMUXC_SetPinMux (IOMUXC_GPIO_EMC_B2_10_GPIO_MUX2_IO20, 1);	// IOMUXC_GPIO_EMC_B2_10_FLEXSPI2_A_SCLK	-	IOMUXC_GPIO_SD_B1_01_FLEXSPI2_A_SCLK

	// Set the direction of 3 pins used in JEDEC reset to output
	GPIO_PinInit (GPIO2, 21, &jreset_pin_config); // CS			- 15-->21
	GPIO_PinInit (GPIO2, 23, &jreset_pin_config); // SI/IO0		- 17-->23
	GPIO_PinInit (GPIO2, 20, &jreset_pin_config); // SCK		- 16-->20


	// Perform a reset sequence:
	// CS goes low 4 times with alternating values of SOUT
	// SCK is drive low or high and must stay in one state
	GPIO_WritePinOutput (GPIO2, 20, 0); // set SCK low
	for (uint32_t i = 0; i < 4; i++)
	{
		// drive CS low
		GPIO_WritePinOutput (GPIO2, 21, 0);
		SDK_DelayAtLeastUs (1, SystemCoreClock);
		// drive SI low or high: alternate its state every iteration
		GPIO_WritePinOutput (GPIO2, 23, (i&1));
		// drive CS high; SI state will be captured on the CS rising edge
		GPIO_WritePinOutput (GPIO2, 21, 1);
		SDK_DelayAtLeastUs (1, SystemCoreClock);
	}

	SDK_DelayAtLeastUs (110, SystemCoreClock);
}